[package]
name = "ero-lapin"
version = "0.1.4"
authors = ["Alexey Voznyuk <me@swizard.info>"]
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git" }
log = "0.4"
tokio = "0.1"
futures = "0.1"
lapin-futures = "0.14"

[dev-dependencies]
pretty_env_logger = "0.2"
